version: "3.8"

services:
    db:
      image: postgres:alpine3.17
      container_name: documents-db
      restart: always
      env_file:
        - .env
      volumes:
        - documents-db:/var/lib/mysql
      ports:
        - "5433:5432"
    
    web:
      restart: always
      container_name: documents-app
      build:
        context: .
      ports:
        - "8000:8000"
      depends_on:
        - db


volumes:
  documents-db: